language: go

go:
    - "1.x"
    #- "1.11"

services:
    - docker

before_install:
    - apt-get update
    - apt-get install -y libyara-dev

install:
    - ./prepare.sh

script:
    - go test -v ./...
    - ./buildForWindows.sh
