language: go

go:
    - "1.x"
    - "1.15"

env:
    - OPENSSL_VERSION=OpenSSL_1_1_1-stable YARA_VERSION=v4.1.0

services:
    - docker

before_install:
    - echo $TRAVIS_GO_VERSION
    - sudo apt-get update
    - sudo apt-get install -y libssl-dev libprotobuf-dev flex bison p7zip-full # libyara-dev package is too old
    - mkdir deps
    - git clone --depth=1 --branch $YARA_VERSION https://github.com/VirusTotal/yara.git deps/yara
    - pushd deps/yara
    - ./bootstrap.sh
    - ./configure --prefix=/usr --with-crypto || exit $?
    - make -j${BUILD_THREADS:-1} || exit $?
    - sudo make install || exit $?
    - popd
    - pkg-config --cflags --libs yara

install:
    - go mod vendor

script:
    - coverpkg="github.com/fkie-cad/yapscan/..."
    - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg="$coverpkg" -v $(go list ./... | grep -v /acceptanceTests)
    - pushd acceptanceTests
    - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg="$coverpkg" -v -quickchecks=${QUICKCHECKS:-100} -short .
    - popd
    - cat acceptanceTests/coverage.txt | tail -n+2 >> coverage.txt
    - rm acceptanceTests/coverage.txt
    - mkdir -p build/ &>/dev/null
    - pushd cmd/yapscan
    - go build -trimpath -o ../../cicd/build/yapscan
    - popd
    - pushd cicd/
    - ./crossBuildForWindows.sh
    - popd

after_success:
    - bash <(curl -s https://codecov.io/bash)

before_deploy:
    - pushd cicd/build
    - 7z a yapscan_windows_amd64.zip yapscan.exe yapscan.dll
    - 7z a yapscan_linux_amd64.zip yapscan
    - tar -cvzf yapscan_windows_amd64.tar.gz yapscan.exe yapscan.dll
    - tar -cvzf yapscan_linux_amd64.tar.gz yapscan
    - popd

deploy:
    provider: releases
    skip_cleanup: true
    api_key:
        secure: SEqzkWiVZTZlK3FvJGku7a10rMVqSPTakdAP2M7p6z+S2SE3yRI4R4aiH3t73Yt2nDPGrW1ie43EsJ0WcPIIVaSHUArNBwdyoGRBtdAq461ZSwsskuMLVz28SreyiTwEb4cmRrx5eggGyAoO6kzuGyBVdnBY8Bzxtj0CVV/qeHxvvD6ARYxBQtq6izomd4hoMnCRKNApIUDFbLo2gnF4YOuAMgi45ALe5jchSHPESsa/e8x2e13WEOCIwmiHxRR4EXS/oOxr8kO792HEa324V7uPE1HaIH3z7fBWWcUMXJZSAYynbzsC2WAHzWgIcFHyqVUcs6IKMU8rweJcNNDIVrC/zY7Jm4/aEdyy/Kq3iReuSUkvv9HY0C+CGf8RK/7x/1LolYXDnXGIeEXF/dkqE4p/bOCKrlW8TePoEf8zUlSiZRd0+XdodyxrbjFdx0E5kePxLGeqkopfR/ubKN5DJY93ueFsVlKYGpWLOKxtZTJoxEcwhSm1EF2Lsd77+xySjeJbh00Ozu51C7lu8Obn4wzWCVLDnlt3X5pSqYEHKphIfVYr21LPD9uQc++XR7IfPQG/Gnz/CTBEGvwTYm29jaD0m5e1pshL5nr5lhCOQIH4iZWSmoCwa8GP3Kbix9tYtPAdOkd6crz3vj0EUEWmd9ioEutTOL3wduGzNTcBvXM=
    file:
        - cicd/build/yapscan_windows_amd64.zip
        - cicd/build/yapscan_windows_amd64.tar.gz
        - cicd/build/yapscan_linux_amd64.zip
        - cicd/build/yapscan_linux_amd64.tar.gz
    on:
        repo: fkie-cad/yapscan
        tags: true
        condition: $TRAVIS_GO_VERSION =~ ^1\.x
