language: go

os: linux
dist: xenial

go:
    - "1.x"
    - "1.15"

env:
    - OPENSSL_VERSION=OpenSSL_1_1_1-stable YARA_VERSION=v4.1.1

services:
    - docker

before_install:
    - echo $TRAVIS_GO_VERSION
    - sudo apt-get update
    - sudo apt-get install -y libssl-dev libprotobuf-dev flex bison p7zip-full # libyara-dev package is too old
    - mkdir deps
    - git clone --depth=1 --branch $YARA_VERSION https://github.com/VirusTotal/yara.git deps/yara
    - pushd deps/yara
    - ./bootstrap.sh
    - ./configure --prefix=/usr --with-crypto || exit $?
    - make -j${BUILD_THREADS:-1} || exit $?
    - sudo make install || exit $?
    - popd
    - pkg-config --cflags --libs yara

install:
    - go mod vendor

script:
    - coverpkg="github.com/fkie-cad/yapscan/..."
    - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg="$coverpkg" -v $(go list ./... | grep -v /acceptanceTests)
    - pushd acceptanceTests
    - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg="$coverpkg" -v -quickchecks=${QUICKCHECKS:-100} -short .
    - popd
    - cat acceptanceTests/coverage.txt | tail -n+2 >> coverage.txt
    - rm acceptanceTests/coverage.txt
    - mkdir -p build/ &>/dev/null
    - pushd cmd/yapscan
    - go build -trimpath -o ../../cicd/build/yapscan
    - popd
    - pushd cicd/
    - ./crossBuildForWindows.sh
    - popd

after_success:
    - bash <(curl -s https://codecov.io/bash)

before_deploy:
    - pushd cicd/build
    - ldd yapscan
    - cp $(ldd yapscan | grep libyara | cut -d'>' -f2 | cut -d' ' -f2) .
    - ldd libyara.so*
    - cp $(ldd libyara.so* | grep libcrypto | cut -d'>' -f2 | cut -d' ' -f2) .
    - 7z a yapscan_windows_amd64.zip yapscan.exe yapscan.dll
    - 7z a yapscan_linux_amd64.zip yapscan libyara.so* libcrypto.so*
    - tar -cvzf yapscan_windows_amd64.tar.gz yapscan.exe yapscan.dll
    - tar -cvzf yapscan_linux_amd64.tar.gz yapscan libyara.so* libcrypto.so*
    - popd

deploy:
    provider: releases
    token:
        secure: g36k1ZMwK/LWSxsM22sz9h//vOAnil/5mHc28te6HsoXold37Gk/OUC8OdVg0Ff3mbTgF0cL+aWWDVL1w+9z5zQJ6w2eHO8ONX7yzv3x70nWuznoN8x00sYGZ9vnVeGSMFPLIK8XJVvwW7F3cKNkrX2GaJU5E9uWfiyrPi0SxgeWvSveMwyCfwFp7kgYv1NzSpoXQxzozfFltFyBfKYzRxGm4rjf7gcxw6/DF+YsD7odQ6s6lxwLAvILYPM3DKnJaZ2ZFpknLFgl0a43seUgSWZtOqkssvZIrPyGLmorGjbHgmNBknhlRQZDAk0oiZGaLD3pgWCLtRzR+N8QkQ9uRSTuxMnIfWAgTvM8LSA+OJH+13IykwdVZxbEqqtie4Q9EZjjBJ3ikWuEuxnO4jfkQYrB1cgMyuJo3T/Ovh2fbuvERq70asFj+ooIYcVNBEY9bP8de+sobbE93xIQS5GatlAwYn2BDmYQGAkEe3DuOY3LrSt88UaxW5ObWOROHGSv5BWTwuIyhzPjorDQhI2gje+XGtdxdX3K4cMYnWP0+f9H0TscdWNK6Hbde/NUJIYrMpdZJMBi7Rp6yH0klDrLPYKRuWDsa26mSnW4cfXUkxW7WIMCFAaBAeoM0yyipJ4da/2JxLA/7+sgLfntD7CXw+62DS6gP8+dD1XT8hw1eM8=
    file:
        - cicd/build/yapscan_windows_amd64.zip
        - cicd/build/yapscan_windows_amd64.tar.gz
        - cicd/build/yapscan_linux_amd64.zip
        - cicd/build/yapscan_linux_amd64.tar.gz
    on:
        repo: fkie-cad/yapscan
        tags: true
        condition: $TRAVIS_GO_VERSION =~ ^1\.x
